# docker-compose up -d
# docker-compose down

version: '3.1'
services:  
  influx:
    container_name: influx
    hostname: influx
    image: influxdb
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - 18086:8086
    volumes:
      - ./influxdb/influxdb.yml:/etc/influxdb2/config.yml
      - ./influxdb/data:/var/lib/influxdb2
    networks:
      - proxy_network
      - default
      
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    restart: always
    ports:
      - 15433:5432
    volumes:
      - source: oradata
        type: volume
        target: /opt/postgres/oradata
      - ./startupscripts:/opt/oracle/scripts/startup
    environment:
      POSTGRES_USER: ${ELASTICSEARCH_PASSWORD:-elastic}
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
    command: -c config_file=/etc/postgresql/postgresql.conf

  redis:
    container_name: redis
    hostname: redis
    image: redis
    restart: always
    ports:
      - 16380:6379
    deploy:
      resources:
        limits:
          memory: 2g
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - ${KIBANA_PORT:-3306}:3306
    volumes:
      - ./mydata/mysql/log:/var/log/mysql
      - ./mydata/mysql/data:/var/lib/mysql
      - ./mydata/mysql/conf:/etc/mysql/conf.d

networks:
  proxy_network:
    driver: bridge
    internal: true

volumes:
  oradata: